### PR TITLE
Made login optional for league that don't use it

### PR DESCRIPTION
**Pull request by JimToupet**
Leagues that don't use login can't no more use the WebClient.

### CODE REVIEW

**Review by SimonT-STHS — COMMENTED** [review]
Hi Jim,

The WebClient always request a password to used. Why do you want to add an option to remove this feature?

**Comment by JimToupet** [comment]
Maybe if password is set but no GM never set password in any version and before 3.2.9 anyone was able to do their rosters/lines without issue. Since 3.2.9 it's impossible to use it without password. Forcing password for the WebClient is a regression of functionality versus the desktop client where anybody can do lines for any if password is not set. Leagues that don't use the Trade or News features, password is not really used.

**Comment by SimonT-STHS** [comment]
Hi Jim.

I disagree, The WebClient always request a password. Before, it was using it's own code based on the GM Password, now. It's using the cookie feature.

**Comment by JimToupet** [comment]
You can test it by yourself :

http://lhssf.com/website328 =>Dynamic Website with 3.2.8 version without any password. The WebClient works. 
http://lhssf.com/website329 =>Dynamic Website with 3.2.9 version without any password. The WebClient don't works.

**Comment by SimonT-STHS** [comment]
Hi Jim.

I'll close this pull request but I create this feature for 3.3.1 where you'll have an option in the STHS "Do Not Required Login to access Web Client and Upload Lines Function" that will allow you achieve this goal.

**Pull request closed without merging**
